//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/LNX/Documents/Rider/Coba-Projekt/Compiler/Parser/Grammar/Julia.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JuliaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IJuliaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] JuliaParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] JuliaParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] JuliaParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] JuliaParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] JuliaParser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] JuliaParser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf([NotNull] JuliaParser.IfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf([NotNull] JuliaParser.IfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile([NotNull] JuliaParser.WhileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile([NotNull] JuliaParser.WhileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] JuliaParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] JuliaParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody([NotNull] JuliaParser.BodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody([NotNull] JuliaParser.BodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] JuliaParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] JuliaParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] JuliaParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] JuliaParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] JuliaParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] JuliaParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] JuliaParser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] JuliaParser.CallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn([NotNull] JuliaParser.ReturnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn([NotNull] JuliaParser.ReturnContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>BoolExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolExpr([NotNull] JuliaParser.BoolExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>BoolExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolExpr([NotNull] JuliaParser.BoolExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ConstExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstExpr([NotNull] JuliaParser.ConstExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ConstExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstExpr([NotNull] JuliaParser.ConstExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MultExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultExpr([NotNull] JuliaParser.MultExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MultExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultExpr([NotNull] JuliaParser.MultExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VarExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarExpr([NotNull] JuliaParser.VarExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VarExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarExpr([NotNull] JuliaParser.VarExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CallExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallExpr([NotNull] JuliaParser.CallExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CallExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallExpr([NotNull] JuliaParser.CallExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddExpr([NotNull] JuliaParser.AddExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddExpr([NotNull] JuliaParser.AddExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CompExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompExpr([NotNull] JuliaParser.CompExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CompExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompExpr([NotNull] JuliaParser.CompExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpr([NotNull] JuliaParser.NotExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NotExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpr([NotNull] JuliaParser.NotExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenExpr([NotNull] JuliaParser.ParenExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenExpr([NotNull] JuliaParser.ParenExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.multOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultOp([NotNull] JuliaParser.MultOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.multOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultOp([NotNull] JuliaParser.MultOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddOp([NotNull] JuliaParser.AddOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.addOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddOp([NotNull] JuliaParser.AddOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompOp([NotNull] JuliaParser.CompOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.compOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompOp([NotNull] JuliaParser.CompOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.boolOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolOp([NotNull] JuliaParser.BoolOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.boolOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolOp([NotNull] JuliaParser.BoolOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.const"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConst([NotNull] JuliaParser.ConstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.const"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConst([NotNull] JuliaParser.ConstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.intValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntValue([NotNull] JuliaParser.IntValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.intValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntValue([NotNull] JuliaParser.IntValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.floatValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatValue([NotNull] JuliaParser.FloatValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.floatValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatValue([NotNull] JuliaParser.FloatValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] JuliaParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] JuliaParser.TypeContext context);
}
