//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/LNX/Documents/Rider/Coba-Projekt/Parser/Grammar/Julia.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JuliaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IJuliaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.chat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChat([NotNull] JuliaParser.ChatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.chat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChat([NotNull] JuliaParser.ChatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] JuliaParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] JuliaParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] JuliaParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] JuliaParser.NameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.opinion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpinion([NotNull] JuliaParser.OpinionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.opinion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpinion([NotNull] JuliaParser.OpinionContext context);
}
