//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/LNX/Documents/Rider/Coba-Projekt/Parser/Grammar/Julia.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JuliaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IJuliaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] JuliaParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] JuliaParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction([NotNull] JuliaParser.FunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction([NotNull] JuliaParser.FunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameters([NotNull] JuliaParser.ParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameters([NotNull] JuliaParser.ParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.return_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn_type([NotNull] JuliaParser.Return_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.return_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn_type([NotNull] JuliaParser.Return_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf([NotNull] JuliaParser.IfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf([NotNull] JuliaParser.IfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile([NotNull] JuliaParser.WhileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile([NotNull] JuliaParser.WhileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] JuliaParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] JuliaParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] JuliaParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] JuliaParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] JuliaParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] JuliaParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] JuliaParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] JuliaParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall([NotNull] JuliaParser.CallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall([NotNull] JuliaParser.CallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn([NotNull] JuliaParser.ReturnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn([NotNull] JuliaParser.ReturnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] JuliaParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] JuliaParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.const"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConst([NotNull] JuliaParser.ConstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.const"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConst([NotNull] JuliaParser.ConstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JuliaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] JuliaParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JuliaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] JuliaParser.TypeContext context);
}
